redismaster:
  deployment:
    repository: gcr.io/kubernetes-e2e-test-images/redis
    tag: "1.0"
    pullPolicy: Always
  service:
    type: ClusterIP

frontend:
  deployment:
    repository: gcr.io/google-samples/gb-frontend
    tag: v6
    pullPolicy: Always
  service:
    type: NodePort

redisslave:
  deployment:
    repository: gcr.io/google_samples/gb-redisslave
    tag: v3
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP

